// import Footer from '@/components/Footer'
// import Navbar from '@/components/Navbar'
import Content from '@/components/Content'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Al Momin Optics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sidelogo.png" />
      </Head>
      {/* <Navbar/> */}
   <div className=""></div>
   <div className="h-3/4">
<img src="/coverz.jpg" alt=""/>
</div>
    <Content/>
    {/* <Footer/> */}
    </>
  )
}
